---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На сайте можно выполнить регистрацию
  - Элементы в мобильной версии сайта должны подстраиваться под верстку
  - Язык на сайте должен определяться в зависимости от географического положения пользователя
  - Строка с поиском по товару должна располагаться над списком товаров посередине
  - В списке товаров нужно выводить бренд
  - На сайте должна быть возможность просматривать список заказов
  - На сайте должна быть возомжность оплаты
  - На сайте должна быть возможность указать пункт выдачи или адрес доставки заказа
